### PR TITLE
create ghost tokyo

### PR DESCRIPTION
**Pull request by DrowningToast**
funny anime song haha

### CODE REVIEW

**Review by leomotors — APPROVED** [review]
APPROVE

**Comment by narze** [comment]
image
Let me fix this first 😶‍🌫️

**Comment by leomotors** [comment]
:armweed:

**Comment by narze** [comment]
image

Whyyyyyyyyyyyyyyyyyyy

**Comment by narze** [comment]
Let's just merge and solve on another PR 🫠

**Pull request merged**
